import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "nextjs-calendar-day-week-month-open-source",
  description: "Generated by DayPilot UI Builder",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body>

      <div className="header">
          <h1><a href='https://code.daypilot.org/62886/next-js-calendar-day-week-month-open-source'>Next.js Calendar with Day/Week/Month Views (Open-Source)</a></h1>
          <div><a href="https://javascript.daypilot.org/">DayPilot for JavaScript</a> - HTML5 Calendar/Scheduling
              Components for JavaScript/Angular/React/Vue
          </div>
      </div>
      <div className="main">
          {children}
          <div className="generated">Generated using <a href="https://builder.daypilot.org/">DayPilot UI Builder</a>.</div>
      </div>
      </body>
    </html>
);
}
